const PASS='kamlin2026',$=id=>document.getElementById(id);
const db={
 bookings:JSON.parse(localStorage.getItem('kamlin_bookings')||'[]'),
 clients:JSON.parse(localStorage.getItem('kamlin_clients')||'[]'),
 workers:JSON.parse(localStorage.getItem('kamlin_workers')||'[]'),
 attendance:JSON.parse(localStorage.getItem('kamlin_attendance')||'[]'),
 assignments:JSON.parse(localStorage.getItem('kamlin_assignments')||'[]'),
 insurance:JSON.parse(localStorage.getItem('kamlin_insurance')||'[]'),
 inventory:JSON.parse(localStorage.getItem('kamlin_inventory')||'[]'),
 contracts:JSON.parse(localStorage.getItem('kamlin_contracts')||'[]')
};
const save=k=>localStorage.setItem('kamlin_'+k,JSON.stringify(db[k]));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>(Number(n)||0).toLocaleString('ar-EG')+' ج';
const cleanPhone=s=>String(s||'').replace(/[^\d+]/g,'');
const del=(k,i)=>{if(confirm('هل تريد الحذف؟')){db[k].splice(i,1);save(k);renderAll()}};
const statusBadge=s=>`<span class="badge">${esc(s)}</span>`;

$('loginForm').addEventListener('submit',e=>{e.preventDefault();if($('adminPassword').value===PASS){sessionStorage.setItem('kamlin_admin','1');openAdmin()}else alert('كلمة المرور غير صحيحة')});
function openAdmin(){$('loginScreen').classList.add('hidden');$('adminApp').classList.remove('hidden');seed();renderAll()}
function logoutAdmin(){sessionStorage.removeItem('kamlin_admin');location.reload()}
if(sessionStorage.getItem('kamlin_admin')==='1')openAdmin();

function seed(){
 if(!db.clients.length){db.clients=[{name:'عميل تجريبي - شركة بالجيزة',sector:'شركة',city:'الجيزة',phone:'',email:'',status:'جديد',followup:'',value:15000,notes:'يمكن حذف هذا الصف'}];save('clients')}
 if(!db.workers.length){db.workers=[{name:'عامل تجريبي',phone:'',job:'عامل نظافة',salary:10000,start:'',status:'نشط',nationalId:'',notes:'يمكن حذف هذا الصف'}];save('workers')}
 if(!db.inventory.length){db.inventory=[{name:'ماكينة شفط وغسيل',category:'معدات',qty:1,min:1,unit:'قطعة',assigned:'',condition:'جيدة',notes:''}];save('inventory')}
}

const titles={dashboard:'لوحة المتابعة',bookings:'طلبات الحجز',clients:'إدارة العملاء',workers:'إدارة العمال',attendance:'الحضور والغياب',assignments:'توزيع مواقع العمل',insurance:'التأمينات والرواتب',inventory:'الأدوات والمخزون',contracts:'العقود والفواتير',quotes:'عروض الأسعار'};
document.querySelectorAll('#adminNav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#adminNav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.admin-view').forEach(v=>v.classList.remove('active'));$('view-'+b.dataset.view).classList.add('active');$('viewTitle').textContent=titles[b.dataset.view];document.body.classList.remove('sidebar-open')});
$('todayText').textContent=new Date().toLocaleDateString('ar-EG',{weekday:'long',year:'numeric',month:'long',day:'numeric'});

function workerName(id){return db.workers.find(w=>String(w.id)===String(id))?.name||'غير محدد'}
function fillWorkerSelects(){['attWorker','asWorker','insWorker'].forEach(id=>{$(id).innerHTML='<option value="">اختر العامل</option>'+db.workers.map(w=>`<option value="${w.id}">${esc(w.name)}</option>`).join('')})}
function renderDashboard(){
 $('dBookings').textContent=db.bookings.length;$('dClients').textContent=db.clients.length;$('dWorkers').textContent=db.workers.filter(w=>w.status==='نشط').length;$('dContracts').textContent=db.contracts.filter(c=>c.status==='نشط').length;$('dPipeline').textContent=money(db.clients.reduce((s,c)=>s+(+c.value||0),0));
 const today=new Date().toISOString().slice(0,10);$('dPresent').textContent=db.attendance.filter(a=>a.date===today&&a.status==='حاضر').length;
 $('todayTasks').innerHTML=db.assignments.filter(a=>a.date===today).map(a=>`<div><b>${esc(workerName(a.worker))}</b> — ${esc(a.site)}<br><small>${esc(a.start)} إلى ${esc(a.end)} | ${esc(a.address)}</small></div>`).join('')||'<p>لا توجد مهام مسجلة اليوم.</p>';
 $('followups').innerHTML=db.clients.filter(c=>c.followup&&c.followup<=today&&!['تم التعاقد','رفض'].includes(c.status)).slice(0,8).map(c=>`<div><b>${esc(c.name)}</b> — ${statusBadge(c.status)}<br><small>${esc(c.phone)} | ${esc(c.followup)}</small></div>`).join('')||'<p>لا توجد متابعات مستحقة.</p>';
}
function renderBookings(){$('bookingsRows').innerHTML=db.bookings.map((b,i)=>`<tr><td><b>${esc(b.name)}</b><br><small>${esc(b.notes)}</small></td><td>${esc(b.phone)}</td><td>${esc(b.place)}</td><td>${esc(b.service)}</td><td>${esc(b.area)}</td><td>${esc(b.date)}</td><td><select onchange="db.bookings[${i}].status=this.value;save('bookings');renderAll()">${['جديد','تم التواصل','تم التأكيد','مكتمل','ملغي'].map(s=>`<option ${b.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td class="table-actions"><a href="tel:${cleanPhone(b.phone)}">اتصال</a><a target="_blank" href="https://wa.me/${cleanPhone(b.phone).replace('+','')}">واتساب</a><button class="delete" onclick="del('bookings',${i})">حذف</button></td></tr>`).join('')||'<tr><td colspan="8">لا توجد طلبات بعد.</td></tr>'}
$('clientForm').onsubmit=e=>{e.preventDefault();const c={id:$('clientId').value||Date.now(),name:$('clientName').value,sector:$('clientSector').value,city:$('clientCity').value,phone:$('clientPhone').value,email:$('clientEmail').value,status:$('clientStatus').value,followup:$('clientFollowup').value,value:$('clientValue').value,notes:$('clientNotes').value};const i=db.clients.findIndex(x=>String(x.id)===String(c.id));i>=0?db.clients[i]=c:db.clients.unshift(c);save('clients');clearClient();renderAll()};
function clearClient(){$('clientForm').reset();$('clientId').value=''}
function editClient(i){const c=db.clients[i];Object.entries(c).forEach(([k,v])=>{const map={id:'clientId',name:'clientName',sector:'clientSector',city:'clientCity',phone:'clientPhone',email:'clientEmail',status:'clientStatus',followup:'clientFollowup',value:'clientValue',notes:'clientNotes'};if($(map[k]))$(map[k]).value=v});scrollTo(0,0)}
function renderClients(){const q=($('clientSearch')?.value||'').toLowerCase();$('clientsRows').innerHTML=db.clients.map((c,i)=>({c,i})).filter(x=>JSON.stringify(x.c).toLowerCase().includes(q)).map(({c,i})=>`<tr><td><b>${esc(c.name)}</b><br><small>${esc(c.city)} | ${esc(c.email)}</small></td><td>${esc(c.sector)}</td><td>${esc(c.phone)}</td><td>${statusBadge(c.status)}</td><td>${esc(c.followup)}</td><td>${money(c.value)}</td><td class="table-actions"><a href="tel:${cleanPhone(c.phone)}">اتصال</a><a target="_blank" href="https://wa.me/${cleanPhone(c.phone).replace('+','')}">واتساب</a><button onclick="editClient(${i})">تعديل</button><button class="delete" onclick="del('clients',${i})">حذف</button></td></tr>`).join('')}
$('workerForm').onsubmit=e=>{e.preventDefault();const w={id:$('workerId').value||Date.now(),name:$('workerName').value,phone:$('workerPhone').value,job:$('workerJob').value,salary:$('workerSalary').value,start:$('workerStart').value,status:$('workerStatus').value,nationalId:$('workerNationalId').value,notes:$('workerNotes').value};const i=db.workers.findIndex(x=>String(x.id)===String(w.id));i>=0?db.workers[i]=w:db.workers.unshift(w);save('workers');clearWorker();renderAll()};
function clearWorker(){$('workerForm').reset();$('workerId').value=''}
function editWorker(i){const w=db.workers[i],map={id:'workerId',name:'workerName',phone:'workerPhone',job:'workerJob',salary:'workerSalary',start:'workerStart',status:'workerStatus',nationalId:'workerNationalId',notes:'workerNotes'};Object.entries(w).forEach(([k,v])=>{$(map[k]).value=v});scrollTo(0,0)}
function renderWorkers(){$('workersRows').innerHTML=db.workers.map((w,i)=>`<tr><td><b>${esc(w.name)}</b><br><small>${esc(w.nationalId)}</small></td><td>${esc(w.phone)}</td><td>${esc(w.job)}</td><td>${money(w.salary)}</td><td>${statusBadge(w.status)}</td><td>${esc(w.start)}</td><td class="table-actions"><button onclick="editWorker(${i})">تعديل</button><button class="delete" onclick="del('workers',${i})">حذف</button></td></tr>`).join('')}
$('attendanceForm').onsubmit=e=>{e.preventDefault();db.attendance.unshift({id:Date.now(),worker:$('attWorker').value,date:$('attDate').value,status:$('attStatus').value,in:$('attIn').value,out:$('attOut').value,hours:$('attHours').value,notes:$('attNotes').value});save('attendance');e.target.reset();renderAll()};
function renderAttendance(){$('attendanceRows').innerHTML=db.attendance.map((a,i)=>`<tr><td>${esc(workerName(a.worker))}</td><td>${esc(a.date)}</td><td>${statusBadge(a.status)}</td><td>${esc(a.in)}</td><td>${esc(a.out)}</td><td>${esc(a.hours)}</td><td class="table-actions"><button class="delete" onclick="del('attendance',${i})">حذف</button></td></tr>`).join('')}
$('assignmentForm').onsubmit=e=>{e.preventDefault();db.assignments.unshift({id:Date.now(),worker:$('asWorker').value,date:$('asDate').value,site:$('asSite').value,address:$('asAddress').value,start:$('asStart').value,end:$('asEnd').value,supervisor:$('asSupervisor').value,notes:$('asNotes').value});save('assignments');e.target.reset();renderAll()};
function renderAssignments(){$('assignmentsRows').innerHTML=db.assignments.map((a,i)=>`<tr><td>${esc(workerName(a.worker))}</td><td>${esc(a.date)}</td><td><b>${esc(a.site)}</b></td><td>${esc(a.address)}</td><td>${esc(a.start)} - ${esc(a.end)}</td><td>${esc(a.supervisor)}</td><td class="table-actions"><button class="delete" onclick="del('assignments',${i})">حذف</button></td></tr>`).join('')}
$('insuranceForm').onsubmit=e=>{e.preventDefault();db.insurance.unshift({id:Date.now(),worker:$('insWorker').value,month:$('insMonth').value,salary:$('insSalary').value,insurance:$('insInsurance').value,bonus:$('insBonus').value,deduction:$('insDeduction').value,status:$('insStatus').value});save('insurance');e.target.reset();renderAll()};
function renderInsurance(){$('insuranceRows').innerHTML=db.insurance.map((x,i)=>`<tr><td>${esc(workerName(x.worker))}</td><td>${esc(x.month)}</td><td>${money((+x.salary||0)+(+x.bonus||0)-(+x.deduction||0))}</td><td>${money(x.insurance)}</td><td>${statusBadge(x.status)}</td><td class="table-actions"><button class="delete" onclick="del('insurance',${i})">حذف</button></td></tr>`).join('')}
$('inventoryForm').onsubmit=e=>{e.preventDefault();db.inventory.unshift({id:Date.now(),name:$('invName').value,category:$('invCategory').value,qty:$('invQty').value,min:$('invMin').value,unit:$('invUnit').value,assigned:$('invAssigned').value,condition:$('invCondition').value,notes:$('invNotes').value});save('inventory');e.target.reset();renderAll()};
function renderInventory(){$('inventoryRows').innerHTML=db.inventory.map((x,i)=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.category)}</td><td>${esc(x.qty)} ${esc(x.unit)}</td><td>${esc(x.min)}</td><td>${statusBadge((+x.qty<=+x.min?'مخزون منخفض - ':'')+x.condition)}</td><td>${esc(x.assigned)}</td><td class="table-actions"><button class="delete" onclick="del('inventory',${i})">حذف</button></td></tr>`).join('')}
$('contractForm').onsubmit=e=>{e.preventDefault();db.contracts.unshift({id:Date.now(),client:$('conClient').value,service:$('conService').value,start:$('conStart').value,end:$('conEnd').value,value:$('conValue').value,status:$('conStatus').value,invoice:$('conInvoice').value,payment:$('conPayment').value,notes:$('conNotes').value});save('contracts');e.target.reset();renderAll()};
function renderContracts(){$('contractsRows').innerHTML=db.contracts.map((c,i)=>`<tr><td><b>${esc(c.client)}</b><br><small>فاتورة: ${esc(c.invoice)}</small></td><td>${esc(c.service)}</td><td>${esc(c.start)} — ${esc(c.end)}</td><td>${money(c.value)}</td><td>${statusBadge(c.status)}</td><td>${statusBadge(c.payment)}</td><td class="table-actions"><button class="delete" onclick="del('contracts',${i})">حذف</button></td></tr>`).join('')}
$('quoteForm').onsubmit=e=>{e.preventDefault();$('quotePreview').innerHTML=`<div class="quote-paper"><header><div><h1>شركة كاملين للنظافة الفائقة</h1><p>عرض سعر رقم K-${Date.now().toString().slice(-6)}</p></div><div><b>KAMLIN</b><br><small>${new Date().toLocaleDateString('ar-EG')}</small></div></header><h2>السادة / ${esc($('qClient').value)}</h2><p>يسعدنا تقديم عرضنا لخدمة: <b>${esc($('qService').value)}</b></p><p>${esc($('qDetails').value).replace(/\n/g,'<br>')}</p><p>مدة التعاقد: <b>${esc($('qDuration').value)}</b></p><p class="amount">إجمالي العرض: ${money($('qAmount').value)}</p><hr><p>الهاتف: +20 101 042 0272 — القاهرة والجيزة</p><button onclick="window.print()">طباعة / حفظ PDF</button></div>`};
function exportTable(k){const arr=db[k];if(!arr.length)return alert('لا توجد بيانات للتصدير');const keys=[...new Set(arr.flatMap(Object.keys))];const csv='\ufeff'+keys.join(',')+'\n'+arr.map(o=>keys.map(x=>`"${String(o[x]??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='kamlin_'+k+'.csv';a.click()}
function renderAll(){fillWorkerSelects();renderDashboard();renderBookings();renderClients();renderWorkers();renderAttendance();renderAssignments();renderInsurance();renderInventory();renderContracts()}
